### ISSUE TITLE
Debian Jessie compilation error

### ISSUE THREAD

**Issue by icefinger** [CipherShed/CipherShed#41]
Dear dev,
The Jessie contains only wx3.0, that changed the access to a constructor to a ::Get (), resulting on a compilation error:
/usr/include/wx-3.0/wx/unix/stdpaths.h:56:5: error: ‘wxStandardPaths::wxStandardPaths()’ is protected

as far I could saw this error concern Main/Application.cpp

**Comment by srguglielmo** [comment]
Hm, CipherShed should be working with wxWidgets 3.0. I have a system that runs Deb Jessie, I'll look into this. It may  be that you have to download the wxWidgets source and have CipherShed build it itself instead of relying on the Debian packages of it.

**Comment by srguglielmo** [comment]
Also, all bug reports should be on our [issue tracker](https://issues.ciphershed.org), not GitHub. Just FYI.

**Comment by srguglielmo** [comment]
Moved to https://issues.ciphershed.org/issues/105

**Comment by Achaean** [comment]
**Hi!** :-)

Just a question:
How is possible to build CipherShed, without relying on Debian packages?
Any details?

**TIA!**
A.

**Comment by GigabyteProductions** [comment]
You could download the source to the old libraries, compile those, and install those onto your system. However, this is not necessary. I made CipherShed compatible with wx3.0, (and GCC5) in 63076fbd1d245083434f156297aee2ed447d5d51 and it's parents (https://github.com/GigabyteProductions/CipherShed/tree/development).

**Comment by GigabyteProductions** [comment]
These commits are now present in development branch.
